require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - ".bundle/**/*"
    - ".github/**/*"
    - "bin/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - simple_enumeration.gemspec
    - "spec/**/*.rb"

RSpec/MultipleExpectations:
  Max: 20

RSpec/ExampleLength:
  Max: 50
